# Generated by Django 3.2.19 on 2023-06-22 07:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='REST_API_mysql_model',
            new_name='Mysql_model',
        ),
    ]
