# Generated by Django 3.2.19 on 2023-06-22 10:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api_app', '0003_auto_20230622_0800'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='Mysql_model',
            table='student_new'
        ),
    ]
