# Generated by Django 3.2.19 on 2023-06-22 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_app', '0004_alter_mysql_model_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mysql_model',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='mysql_model',
            name='name',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='mysql_model',
            name='subject',
            field=models.CharField(max_length=30),
        ),
    ]
