# Generated by Django 3.2.19 on 2023-06-22 11:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api_app', '0006_alter_mysql_model_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mysql_model',
            options={},
        ),
    ]
