# Generated by Django 3.2.19 on 2023-06-22 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_app', '0008_alter_mysql_model_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mysql_model',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
